// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SsoBarbearia.Infraestrutura.Contexto;

#nullable disable

namespace SsoBarbearia.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SsoBarbearia.Modelos.Entidades.ConfiguracaoSite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CorAcento")
                        .HasColumnType("text");

                    b.Property<string>("CorFundo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CorPrimaria")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CorSecundaria")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CorTexto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DominioId")
                        .HasColumnType("integer");

                    b.Property<byte[]>("Logo")
                        .HasColumnType("bytea");

                    b.Property<string>("NomeSite")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DominioId");

                    b.ToTable("ConfiguracaoSite");
                });

            modelBuilder.Entity("SsoBarbearia.Modelos.Entidades.DominioAutorizado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Dominio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DominioAutorizado");
                });

            modelBuilder.Entity("SsoBarbearia.Modelos.Entidades.ConfiguracaoSite", b =>
                {
                    b.HasOne("SsoBarbearia.Modelos.Entidades.DominioAutorizado", "Dominio")
                        .WithMany()
                        .HasForeignKey("DominioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dominio");
                });
#pragma warning restore 612, 618
        }
    }
}
